version: '3'

services:
  web:
    build: .
    container_name: oidc-client-web

  nginx:
    depends_on:
      - web
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl:/etc/nginx/certs

networks:
  network1:
    external: true